name: ${project.name}
main: net.daboross.bukkitdev.entitylist.EntityList
version: ${project.version}
author: Dabo Ross
description: Lists entities in all worlds
commands:
  entitylist:
    permission: entitylist.use
